### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by tomsq** [hbourgeot/gonertia_vue_example#1]
Thanks for the great adapter!

I am trying it out and I stumbled on a HMR not working when running a dev mode. 

Is it possible to get hot reloading working?

**Comment by henrriusdev** [comment]
Thanks for using this repo template! The adapter is built by @romsar 

The hot reloading is a issue that I've already fixed but not uploaded to the templates, you can check this issue of the svelte gonertia template, it fixes the HMR https://github.com/henrriusdev/gonertia_svelte_example/issues/1

I'm going today to update the templates with that addition
